export const colorRoles = {
	b: {
		name: "background",
		default: { h: 0, c: 0, l: 1.0, a: 1.0 },
		extend: true,
		invert: "m",
	},
	c: {
		name: "sheet",
		default: { h: 0, c: 0, l: 0.95, a: 1.0 },
		extend: true,
		invert: "a",
	},
	t: {
		name: "text",
		default: { h: 0, c: 0, l: 0.4, a: 1.0 },
		extend: true,
		invert: "i",
	},
	h: {
		name: "highlight",
		default: { h: 6, c: 0.4, l: 0.33, a: 1.0 },
		extend: true,
		invert: "e",
	},
	m: {
		name: "main",
		default: { h: 30, c: 0.1, l: 0.2, a: 1.0 },
		extend: true,
		invert: "b",
	},
	a: {
		name: "accent",
		default: { h: 32, c: 0.4, l: 0.5, a: 1.0 },
		extend: true,
		invert: "s",
	},
	i: {
		name: "inside",
		default: { h: 0, c: 0, l: 1.0, a: 1.0 },
		extend: true,
		invert: "t",
	},
	e: {
		name: "emphasis",
		default: { h: 12, c: 0.4, l: 0.5, a: 1.0 },
		extend: true,
		invert: "h",
	},
	l: {
		name: "line",
		default: { h: 0, c: 0, l: 0.4, a: 1.0 },
		extend: true,
		invert: "r",
	},
	r: {
		name: "rule",
		default: { h: 0, c: 0, l: 1.0, a: 1.0 },
		extend: true,
		invert: "l",
	},
	lt: {
		name: "light",
		default: { h: 0, c: 0, l: 1.0, a: 0.6 },
		extend: false,
		invert: null,
	},
	lst: {
		name: "lust",
		default: { h: 0, c: 0, l: 1.0, a: 0.9 },
		extend: false,
		invert: null,
	},
	sh: {
		name: "shade",
		default: { h: 0, c: 0, l: 0.0, a: 0.2 },
		extend: false,
		invert: null,
	},
	shd: {
		name: "shadow",
		default: { h: 0, c: 0, l: 0.0, a: 0.3 },
		extend: false,
		invert: null,
	},
};
